---
- name: Homelab playbook config
  hosts: "{{ variable_host }}"
  vars:
    packages_state: latest   # use "present" or switch to "latest" to update packages when possible
  roles:
    - role: common_variables
    - role: base
      tags: base
    - role: docker_rootless
      tags: docker_rootless
