---
- name: Homelab playbook config
  hosts: "{{ variable_host }}"    # noqa: syntax-check  -> TODO: find a way to make it work despite unskippable
  vars:
    packages_state: present   # use "present" or switch to "latest" to update packages when possible
  roles:
    - role: common_variables
    - role: base
      tags: base
    - role: monitoring
      tags: monitoring
    - role: docker_rootless
      tags: docker_rootless
