---
- name: "Ensure required packages are present"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ packages_state }}"
  loop: "{{ required_packages }}"

- name: "Create Promtail directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
  - "{{ promtail.directory_path }}"
  - "{{ promtail.config_dir }}"

- name: "Get Promtail archive"
  ansible.builtin.uri:
    url: "{{ promtail.release_uri }}"
    dest: "{{ promtail.directory_path }}"

- name: "Unzip Promtail archive"
  ansible.builtin.unarchive:
    src: "{{ promtail.directory_path }}/promtail-linux-amd64.zip"
    dest: "{{ promtail.directory_path }}"
    mode: "0755"
    remote_src: true

- name: "Create Promtail config file"
  ansible.builtin.template:
    src: promtail_config.yaml.j2
    dest: "{{ promtail.config_dir }}/{{ promtail.config_file_name }}"
    mode: "0644"

- name: "Create Promtail service definition"
  ansible.builtin.template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    mode: "0644"

# TODO:
# notify systemctl daemon-reload
# enable & start service
